### PR TITLE
API consistency between costs and constraints

### PR DESCRIPTION
**Pull request by stephane-caron**
This PR addresses issue https://github.com/vsamy/Copra-deprecated/issues/4.

### CODE REVIEW

**Comment by stephane-caron** [comment]
For the CMakeLists, it's the contrary: there was a set before, which yielded the following error for me:
```
CMake Error at CMakeLists.txt:54 (set):
  set given invalid arguments for CACHE mode.
CMake Error at CMakeLists.txt:58 (set):
  set given invalid arguments for CACHE mode.
```
I replaced it by the ``option()``, which fixed it for me (also now you can see it if you do ``ccmake .`` in the build dir).

OK for the tests, I'll go update them.

**Comment by stephane-caron** [comment]
Oh, actually tests are broken upstream in cbc756d3d4ea95a2412944f2e3a7bb2870b2a38e:
```
Running 30 test cases...
/home/tastalian/tmp/Copra-deprecated/tests/TestLMPC.cpp(85): error in "MPC_TARGET_COST_WITH_BOUND_CONSTRAINTS": absolute value of xd(1) - velTraj.tail(1)(0){1.1426169776506434} exceeds 0.001
...
```

**Comment by stephane-caron** [comment]
OK actually that's a separate issue, opened as #7.

**Comment by stephane-caron** [comment]
Tests are now up-to-date!

**Comment by vsamy** [comment]
Thank you very much for your work. 
I guess I will Reup everything without the deprecated in the name. But I need to check if I had made some modifications with the actual non-deprecated version.
